repository:
  name: journal
  description: A simple blog available as an API, written in Go with accompanying tests and documentation. Can be used as a useful starting point for Go web projects.
  #homepage: https://example.github.io/
  topics: golang, unit-testing, rest-api, sqlite
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
labels:
  - name: "📚 documentation"
    color: 0075ca
    description: Improvements or additions to documentation
  - name: "🐛 bug"
    color: d73a4a
    description: Something isn't working
  - name: "⬆️ dependencies"
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: "⚡ enhancement"
    color: a2eeef
    description: Update to existing feature or request
  - name: "✨ feature"
    color: 22dd53
    description: Brand new feature or idea
  - name: "⛔️ invalid"
    color: e4e669
    description: This doesn't seem right
  - name: "🧑‍🤝‍🧑 duplicate"
    color: cfd3d7
    description: This issue or pull request already exists
  - name: "❓ question"
    color: d876e3
    description: More information is needed
  - name: "🤦‍♂️ wontfix"
    color: ffffff
    description: This won't be worked on
  - name: "🚨 tests"
    color: fcb1a8
    description: Updates or adds tests
  - name: "🔨 task"
    color: 4346cc
    description: Technical or build task
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ['Test']
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []