FROM golang:1.22-bookworm
LABEL org.opencontainers.image.source=https://github.com/jamiefdhurst/journal

ENV J_ARTICLES_PER_PAGE ""
ENV J_CREATE ""
ENV J_DB_PATH ""
ENV J_DESCRIPTION ""
ENV J_EDIT ""
ENV J_GA_CODE ""
ENV J_PORT ""
ENV J_THEME ""
ENV J_TITLE ""

WORKDIR /go/src/github.com/jamiefdhurst/journal
COPY . .

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes build-essential libsqlite3-dev; \
    go mod download; \
    CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -v -o journal .; \
    go install github.com/tebeka/go2xunit@latest;\
    go install github.com/axw/gocov/gocov@latest; \
    go install github.com/AlekSi/gocov-xml@latest; \
    mv journal /go/bin/journal

VOLUME /go/data
EXPOSE 3000

CMD ["journal"]
