name: Test

on:
  pull_request: {}

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

env:
  GOPATH: /home/runner/work/journal/journal/go
  J_ARTICLES_PER_PAGE: ''
  J_DB_PATH: ''
  J_PORT: ''
  J_TITLE: ''

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: go/src/github.com/jamiefdhurst/journal
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: go/src/github.com/jamiefdhurst/journal/go.sum
      - name: Install Dependencies
        working-directory: go/src/github.com/jamiefdhurst/journal
        run: |
          go install github.com/tebeka/go2xunit@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
      - name: Test
        working-directory: go/src/github.com/jamiefdhurst/journal
        run: make test
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: go/src/github.com/jamiefdhurst/journal/tests.xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: go/src/github.com/jamiefdhurst/journal/coverage.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          action_fail: true
          files: |
            go/src/github.com/jamiefdhurst/journal/tests.xml
      - name: Create Code Coverage Report
        uses: im-open/code-coverage-report-generator@4.9.0
        with:
          reports: go/src/github.com/jamiefdhurst/journal/coverage.xml
          reporttypes: MarkdownSummary
          title: Go Test Code Coverage
      - name: Publish Code Coverage
        uses: im-open/process-code-coverage-summary@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-file: './coverage-results/Summary.md'
          check-name: 'Code Coverage'
          line-threshold: 80
