name: Test

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request: {}

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

env:
  GOPATH: /home/runner/work/journal/journal/go
  J_ARTICLES_PER_PAGE: ''
  J_DB_PATH: ''
  J_GIPHY_API_KEY: ''
  J_PORT: ''
  J_TITLE: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: go/src/github.com/jamiefdhurst/journal
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install Dependencies
        working-directory: go/src/github.com/jamiefdhurst/journal
        run: |
          go get -v ./...
          go install -v ./...
          go install github.com/tebeka/go2xunit@latest
          go install github.com/t-yuki/gocover-cobertura@latest
      - name: Test
        working-directory: go/src/github.com/jamiefdhurst/journal
        run: make test > tests.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: go/src/github.com/jamiefdhurst/journal/tests.xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            tests.xml
